data:
  train_dir: "/path/to/data/train"
  subset_size: 320

train:
  results_dir: "results"
  epochs: 4000
  diffusion_steps: 1000
  learning_rate: 1e-4
  weight_decay: 1e-5          
  global_batch_size: 32
  num_workers: 4
  log_every: 10
  ckpt_every: 100
  seed: 0

model:
  module: "models.backbones.model_nextune"
  class: "NexTune_models"
  name: "NexTune-S"
  seq_length: 469
  hist_length: 469
  n_mels: 256
  use_ckpt_wrapper: true  
