data:
  test_dir: "/path/to/test/dir"

sample:
  num_sampling: 100
  num_sampling_steps: 1000
  cuda_device: 0
  seed: 0

model:
  ckpt: "/path/to/ckpt"
  module: "models.backbones.model_nextune"
  class: "NexTune_models"
  name: "NexTune-S"
  seq_length: 469
  hist_length: 469
  n_mels: 256
