data:
  train_dir: "/path/to/train/dir"

train:
  results_dir: "results"
  epochs: 4000
  diffusion_steps: 1000
  learning_rate: 1e-4
  weight_decay: 1e-5          # set to 1e-5 if you need L2 regularization (in case of overfitting)
  global_batch_size: 32
  global_seed: 0
  num_workers: 4
  log_every: 100
  ckpt_every: 1000

model:
  module: "models.backbones.model_nextune"
  class: "NexTune_models"
  name: "NexTune-S"
  seq_length: 469
  hist_length: 469
  n_mels: 256
  use_ckpt_wrapper: true  
