data:
  test_dir: "/path/to/test/dir"

sample:
  num_sampling: 100
  num_sampling_steps: 100
  cuda_device: 0
  seed: 0

model:
  ckpt: "/path/to/ckpt"
  module: "models.backbones.model_td"
  class: "NexTune_models"
  name: "NexTune-S"
  max_num_agents: 20
  seq_length: 5
  hist_length: 8
  dim_size: 2
